update ci

diff --git a/.github/workflows/snyk-diff.yml b/.github/workflows/snyk-diff.yml
--- a/.github/workflows/snyk-diff.yml
+++ b/.github/workflows/snyk-diff.yml
@@ -17,12 +17,6 @@ jobs:
           ref: ${{ github.event.pull_request.base.sha }}  # 获取待合入分支的 commit
           fetch-depth: 1  # 只获取基准分支的提交
 
-      # Step 1.1 
-      - name: Verify Checked Out Base Branch
-        run: |
-          echo "Checked out commit:"
-          git log -1
-        
       # Step 2: Set up Go environment
       - name: Setup Go environment
         uses: actions/setup-go@v4
@@ -43,10 +37,22 @@ jobs:
 
       # Step 6: Generate baseline report from the base branch
       - name: Generate Baseline Snyk Report
-        working-directory: ${{ github.workspace }}
-        run: snyk test --package-manager=gomodules --severity-threshold=low --json > baseline-report.json || true
+        run: |
+          echo "Running Snyk test for baseline report..."
+          snyk test --package-manager=gomodules --severity-threshold=low --json | tee baseline-report.json || true
+          echo "Snyk test for baseline completed."
 
-      # Step 7: Checkout the current PR branch and generate the current report
+      # Step 7: Verify if baseline report was generated
+      - name: Check Baseline Report File
+        run: |
+          if [ -f baseline-report.json ]; then
+            echo "Baseline report generated successfully."
+          else
+            echo "Baseline report not found."
+            exit 1
+          fi
+
+      # Step 8: Checkout the current PR branch and generate the current report
       - name: Checkout current PR branch
         uses: actions/checkout@v3
         with:
@@ -56,9 +62,12 @@ jobs:
         run: go mod tidy
 
       - name: Generate Current Snyk Report
-        run: snyk test --package-manager=gomodules --severity-threshold=low --json > current-report.json || true
+        run: |
+          echo "Running Snyk test for current report..."
+          snyk test --package-manager=gomodules --severity-threshold=low --json | tee current-report.json || true
+          echo "Snyk test for current report completed."
 
-      # Step 8: Compare baseline and current reports for new vulnerabilities
+      # Step 9: Compare baseline and current reports for new vulnerabilities
       - name: Compare Snyk Reports for New Vulnerabilities
         run: |
           # 使用 jq 提取 baseline 和 current 的漏洞 ID，并对它们进行排序
